groups:
  - name: "up"
    rules:
      - alert: "DownFor5m"
        expr: up == 0
        for: 5m
        labels:
          severity: "5"
        annotations:
          summary: "{{$labels.instance}} is down"
          description: "{{$labels.instance}} has been down for 5 minutes."

  - name: "http"
    rules:
      - alert: "HttpErrorFor5m"
        expr: probe_success == 0
        for: 5m
        labels:
          severity: "5"
        annotations:
          summary: "{{$labels.instance}} not responding HTTP 200 OK"
          description: "{{$labels.instance}} has not responded with HTTP status code 200 OK for 5 minutes."

  - name: "icmp"
    rules:
      - alert: "NoIcmpFor5m"
        expr: probe_success == 0
        for: 5m
        labels:
          severity: "5"
        annotations:
          summary: "{{$labels.instance}} not replying to ICMP"
          description: "{{$labels.instance}} has not replied to ICMP for 5 minutes."

  - name: "memory"
    rules:
      - alert: "NoMemoryIn15m"
        expr: predict_linear(node_memory_MemAvailable_bytes[1h], 15 * 60) <= 0
        for: 5m
        labels:
          severity: "5"
        annotations:
          summary: "{{$labels.instance}}: No memory in 15m"
          description: "{{$labels.instance}} will run out of available memory in 15 minutes based on the last 15 minutes of of metrics."

      - alert: "NoSwapIn15m"
        expr: predict_linear(node_memory_SwapFree_bytes[1h], 15 * 60) <= 0
        for: 5m
        labels:
          severity: "5"
        annotations:
          summary: "{{$labels.instance}}: No swap in 15m"
          description: "{{$labels.instance}} will run out of available swap memory in 15 minutes based on the last 15 minutes of of metrics."

  - name: "disk"
    rules:
      - alert: "NoSpaceIn24h"
        expr: predict_linear(node_filesystem_avail_bytes{fstype!~"(tmp|root)fs"}[1h], 24 * 3600) <= 0
        for: 5m
        labels:
          severity: "4"
        annotations:
          summary: "{{$labels.instance}}: {{$labels.mountpoint}} no space in 24h"
          description: "{{$labels.mountpoint}} on {{$labels.instance}} will run out of disk space in 24 hours based on the last hour of metrics."

      - alert: "NoSpaceFor5m"
        expr: node_filesystem_avail_bytes{fstype!="tmpfs"} <= 0
        for: 5m
        labels:
          severity: "5"
        annotations:
          summary: "{{$labels.instance}}: {{$labels.mountpoint}} no space"
          description: "{{$labels.mountpoint}} on {{$labels.instance}} is out of free disk space."

