groups:
  - name: "up"
    rules:
      - alert: "Down"
        expr: up == 0
        for: 5m
        labels:
          severity: "critical"
        annotations:
          summary: "{{$labels.instance}} is down."
          description: "{{$labels.instance}} has been down for more than 5 minutes." 

  - name: "disk"
    rules:
      - alert: "DiskFilledIn24h"
        expr: predict_linear(node_filesystem_avail_bytes{job="node",instance="$hostname:9100",fstype!="tmpfs"}[1h], 24 * 3600)
        for: 5m
        labels:
          severity: "critical"
        annotations:
          summary: "{{$labels.instance}}: {{$labels.mountpoint}} will fill in 24h"
          description: "{{$labels.mountpoint}} on {{$labels.instance}} will fill up and run out of space in 24 hours"

      - alert: "DiskSpaceCritical"
        expr: node_filesystem_avail_bytes{job="node",fstype!="tmpfs"} / node_filesystem_size_bytes{job="node",fstype!="tmpfs"} < 0.05
        for: 5m
        labels:
          severity: "critical"
        annotations:
          summary: "{{$labels.instance}}: {{$labels.mountpoint}} below 5%"
          description: "{{$labels.mountpoint}} on {{$labels.instance}} has less than 5% free disk space remaining."

      - alert: "DiskSpaceMajor"
        expr: node_filesystem_avail_bytes{job="node",fstype!="tmpfs"} / node_filesystem_size_bytes{job="node",fstype!="tmpfs"} < 0.10
        for: 5m
        labels:
          severity: "major"
        annotations:
          summary: "{{$labels.instance}}: {{$labels.mountpoint}} below 10%"
          description: "{{$labels.mountpoint}} on {{$labels.instance}} has less than 10% free disk space remaining."

      - alert: "DiskSpaceMinor"
        expr: node_filesystem_avail_bytes{job="node",fstype!="tmpfs"} / node_filesystem_size_bytes{job="node",fstype!="tmpfs"} < 0.20
        for: 5m
        labels:
          severity: "minor"
        annotations:
          summary: "{{$labels.instance}}: {{$labels.mountpoint}} below 20%"
          description: "{{$labels.mountpoint}} on {{$labels.instance}} has less than 20% free disk space remaining."
