groups:
  - name: "disk"
    rules:
      - alert: "DiskSpaceCritical"
        expr: node_filesystem_avail_bytes{job="node",fstype!="tmpfs"} / node_filesystem_size_bytes{job="node",fstype!="tmpfs"} < 0.05
        for: 10m
        labels:
          severity: "critical"
        annotations:
          summary: "Free disk space"

      - alert: "DiskSpaceMajor"
        expr: node_filesystem_avail_bytes{job="node",fstype!="tmpfs"} / node_filesystem_size_bytes{job="node",fstype!="tmpfs"} < 0.10
        for: 10m
        labels:
          severity: "major"
        annotations:
          summary: "Free disk space"

      - alert: "DiskSpaceMinor"
        expr: node_filesystem_avail_bytes{job="node",fstype!="tmpfs"} / node_filesystem_size_bytes{job="node",fstype!="tmpfs"} < 0.20
        for: 10m
        labels:
          severity: "minor"
        annotations:
          summary: "Free disk space"
