version: "3"

services:
  nginx:
    image: "nginx:latest"
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/www:/etc/nginx/www:ro"
      - "./certbot:/etc/letsencrypt:ro"

  certbot:
    image: "certbot/certbot:latest"
    volumes:
      - "./certbot:/etc/letsencrypt:rw"
    command:
      - "renew"
    depends_on:
      - "nginx"

  prometheus:
    image: "prom/prometheus:latest"
    restart: "unless-stopped"
#    ports:
#      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus:ro"
      - "prometheus-data:/prometheus:rw"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.external-url=https://nms.hjkl.se/prometheus"
      - "--web.route-prefix=/"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
      - "--storage.tsdb.retention.time=90d"

  alertmanager:
    image: "prom/alertmanager:latest"
    restart: "unless-stopped"
#    ports:
#      - "9093:9093"
    volumes:
      - "./alertmanager:/etc/alertmanager:ro"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.external-url=https://nms.hjkl.se/alertmanager"
      - "--web.route-prefix=/"

  grafana:
    image: "grafana/grafana:latest"
    restart: "unless-stopped"
#    ports:
#      - "3000:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
      - "grafana-data:/var/lib/grafana:rw"
      - "./grafana/plugins:/var/lib/grafana/plugins:ro"

  blackbox:
    image: "prom/blackbox-exporter:latest"
    restart: "unless-stopped"
#    ports:
#      - "9115:9115"
    volumes:
      - "./blackbox_exporter:/etc/blackbox_exporter:ro"

volumes:
  prometheus-data:
  grafana-data:
