groups:
  - name: "cpu"
    rules:
      - record: recording_node_cpu_usage_percent
        expr: 100 - irate(node_cpu_seconds_total{mode="idle"}[5m]) * 100

  - name: "memory"
    rules:
      - record: recording_node_memory_usage_percent_linux
        expr: 100 - node_memory_MemAvailable_bytes * 100 / node_memory_MemTotal_bytes

      - record: recording_node_swap_usage_percent_linux
        expr: 100 - node_memory_SwapFree_bytes * 100 / node_memory_SwapTotal_bytes

      - record: recording_node_memory_usage_percent_bsd
        expr: node_memory_active_bytes * 100 / node_memory_size_bytes

      - record: recording_node_swap_usage_percent_bsd
        expr: node_memory_swap_used_bytes * 100 / node_memory_swap_size_bytes

  - name: "disk"
    rules:
      - record: recording_node_disk_space_free_percent
        expr: node_filesystem_avail_bytes{fstype!~"(tmp|root)fs"} * 100 / node_filesystem_size_bytes{fstype!~"(tmp|root)fs"}

      - record: recording_node_io_rate_write_linux
        expr: irate(node_disk_written_bytes_total[5m])

      - record: recording_node_io_rate_read_linux
        expr: irate(node_disk_read_bytes_total[5m])

      - record: recording_node_io_rate_write_bsd
        expr: irate(node_devstat_bytes_total{type="write"}[5m])

      - record: recording_node_io_rate_read_bsd
        expr: irate(node_devstat_bytes_total{type="read"}[5m])

  - name: "network"
    rules:
      - record: recording_node_network_transmit_rate
        expr: irate(node_network_transmit_bytes_total{device!~"(lo|br|veth).*"}[5m])

      - record: recording_node_network_receive_rate
        expr: irate(node_network_receive_bytes_total{device!~"(lo|br|veth).*"}[5m])

      - record: recording_node_network_transmit_increase
        expr: increase(node_network_transmit_bytes_total{device!~"(lo|br|veth).*"}[1d])

      - record: recording_node_network_receive_increase
        expr: increase(node_network_receive_bytes_total{device!~"(lo|br|veth).*"}[1d])

