global:
  scrape_interval: "1m"     # default = 10s
  scrape_timeout: "10s"      # default = 10s
  evaluation_interval: "1m"  # default = 1m

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

# Alerting rules
rule_files:
  - "recording/*.yml"
  - "alerting/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "alertmanager"
    static_configs:
      - targets:
          - "alertmanager:9093"

  - job_name: "node"
    file_sd_configs:
      - files:
          - "discovery/node/*.json"

  - job_name: "irc_log"
    static_configs:
      - targets:
          - "hjkl.se:9229"

  - job_name: "n9c"
    scrape_interval: "1h"
    scrape_timeout: "1m"
    scheme: "https"
    static_configs:
      - targets:
        - "nordic9-crawler.herokuapp.com"

  - job_name: "grafana"
    static_configs:
      - targets:
          - "grafana:3000"

  - job_name: "blackbox_icmp"
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - "discovery/blackbox/icmp/*.json"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: "blackbox_http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - "discovery/blackbox/http/*.json"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
